language: nix

os:
  - linux
  - osx

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
  - mkdir -p ~/.config/nixpkgs
  - echo "{}" > ~/.config/nixpkgs/home.nix

script:
  nix-shell . -A install
